# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tatiana's ACA Blog
email: Tatianagwatson@gmail.com
description: > Coding and some coding.
baseurl: "/aca-blog" # the subpath of your site, e.g. /blog
url: "http://tatianagwatson.github.io" # the base hostname & protocol for your site
twitter_username: Dr_Watson00
github_username:  tatianagwatson

# Build settings
markdown: kramdown
